services:
  - type: web
    name: zestyflow-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: zestyflow-backend
          property: port
    # Add your environment variables in the Render dashboard:
    # MONGO_URI - Your MongoDB connection string
    # JWT_SECRET - A secure random string for JWT tokens
    # CLIENT_ORIGIN - Your Render app URL
